---
# used for running tests
name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pre_commit_checks:
    runs-on: ubuntu-24.04
    steps:
      # checks out the repo
      - uses: actions/checkout@v5
      # run pre-commit
      - name: Python setup
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7
      - uses: pre-commit/action@v3.0.1
      # run pre-commit ci lite for automated fixes
      - uses: pre-commit-ci/lite-action@v1.1.0
        if: ${{ !cancelled() }}
